FROM node:18

# Crear y establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos necesarios
COPY package*.json ./
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Compilar TypeScript a JavaScript
RUN npm run build  

# Ejecutar el archivo compilado
CMD ["node", "dist/src/server.js"]
