name: Deploy to EC2

on:
  push:
    branches:
      - main  # O la rama que desees monitorear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Usa la versión más reciente

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Usa la versión más reciente
      with:
        node-version: '20'  # Usa Node.js 20

    - name: Copy files via SCP to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}  # Host de tu instancia EC2
        username: ${{ secrets.EC2_USER }}  # Nombre de usuario en EC2 (generalmente "ec2-user")
        key: ${{ secrets.EC2_SSH_KEY }}  # Clave privada SSH (debería ser una clave PEM)
        source: './'  # Ruta en GitHub donde están los archivos que quieres copiar
        target: '/home/ec2-user/projects/appi-getway'  # Ruta destino en EC2

    - name: Execute SSH commands on EC2 with PM2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}  # Host de tu instancia EC2
        username: ${{ secrets.EC2_USER }}  # Nombre de usuario en EC2
        key: ${{ secrets.EC2_SSH_KEY }}  # Clave privada SSH
        script: |
          cd /home/ec2-user/projects/appi-getway
          npm install  # Asegúrate de que las dependencias estén instaladas
          pm2 restart app  # Reinicia la aplicación para aplicar cambios



