name: Deploy to EC2

on:
  push:
    branches:
      - main   # O la rama que desees monitorear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Se mantiene, ya que es la versión más reciente

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Se mantiene, ya que es la versión más reciente
      with:
        node-version: '20'  # Actualiza a Node.js 20

    - name: Copy files via SSH to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: './'  # Ruta en GitHub donde están los archivos que quieres copiar
        target: '/home/ec2-user/projects/appi-getway'  # Ruta destino en EC2

    - name: Execute SSH commands on EC2 with PM2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/projects/appi-getway
          npm install  # Asegura que las dependencias estén instaladas
          pm2 restart app  # Reinicia la aplicación para aplicar cambios

