name: Deploy to EC2

on:
  push:
    branches:
      - main   # O la rama que desees monitorear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (si usas Node.js)
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Copy files via SSH to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: './'  # Ruta en GitHub donde están los archivos que quieres copiar
        target: '~/projects/appi-getway/'  # Ruta destino en EC2

    - name: Execute SSH commands on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/projects/appi-getway
